### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by breuslife** [jarnoaxel/python-wireguard#29]
**Describe the bug**  
When attempting to run a Python script that uses the `python_wireguard` library on macOS, 
I encounter an `OSError` related to the `py-wireguard.so` shared object file. 
The file appears to be an ELF 64-bit LSB shared object, x86-64, which is typically used on Linux systems.

**To Reproduce**  
1. Install `python_wireguard` in a Python **3.8, 3.9, 3.11** virtual environment on **macOS**.
2. Run a Python script that imports `python_wireguard`.
3. Encounter an `OSError` related to `py-wireguard.so`.

**Code Snippet**
```python
from python_wireguard import Client, ServerConnection, Key
```

**Error Message**
```bash
OSError: dlopen(/path/to/py-wireguard.so, 0x0006): tried: '/path/to/py-wireguard.so' (not a mach-o file), ...
```

**Expected behavior**  
I expect the script to run without issues and the `python_wireguard` library to be loaded successfully.

**Screenshots**  
N/A

**Desktop (please complete the following information):**  
- OS: macOS
- Python Version: 3.8, 3.9, 3.11

**Additional context**  
I have confirmed using `file` and `otool` that the shared object is an ELF 64-bit LSB shared object, x86-64. 
This seems to suggest that the library is incompatible with macOS as it stands.

**Comment by lidj22** [comment]
Same issue on simply importing the library, on an M1 macbook running Python 3.12.

**Comment by KraoESPfan1n** [comment]
similar issue but with this error:
```
Exception has occurred: OSError
[WinError 193] %1 no es una aplicación Win32 válida
  File "C:\Users\Angel\Downloads\vpn.py", line 2, in <module>
    from python_wireguard import Key, Server, ClientConnection, Client, ServerConnection
OSError: [WinError 193] %1 no es una aplicación Win32 válida
```
i have windows 11, 64 bits, and the leatest python version

**Comment by windigerbus** [comment]
Similar issue on Alpine (Docker)

```
Traceback (most recent call last):
  File "/root/app.py", line 1, in <module>
    from python_wireguard import Client, ServerConnection, Key, Server
  File "/usr/lib/python3.11/site-packages/python_wireguard/__init__.py", line 4, in <module>
    from .wireguard import list_devices, delete_device
  File "/usr/lib/python3.11/site-packages/python_wireguard/wireguard.py", line 9, in <module>
    c_library = CDLL(dirname + '/bin/py-wireguard.so')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: Error relocating /usr/lib/python3.11/site-packages/python_wireguard/bin/py-wireguard.so: __printf_chk: symbol not found
```
